### POST: Create 1 product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "name": "Laptop Lenovo",
  "price": 1000,
  "stock": 30,
  "categoryId": 1
}

#########

### DELETE: Delete 1 product by his id
DELETE http://localhost:3000/api/products/1

#########

### PUT: Update 1 product by his id
PUT http://localhost:3000/api/products/4
Content-Type: application/json

{
    "price": 900
}